### ISSUE TITLE
SQL injection from Ingame user name

### ISSUE THREAD

**Issue by faaanbingbing** [szporwolik/perun#27]
User name example:

'; select * from users;--

etc...

**Comment by szporwolik** [comment]
Hmn, I was sure that there is some DCS functionality to prevent this from happening. 
Thanks for information, will include some protection in the next release.

**Comment by szporwolik** [comment]
@faaanbingbing this was fixed in c36befd5a060f2795c495e58c57f87e8fe301656

I will release 0.9.3 with the fix.

Thank you again!
