### ISSUE TITLE
Documentation needed: php example

### ISSUE THREAD

**Issue by ghost** [szporwolik/perun#37]
Hello, a suggestion, would it be possible to add a php file of how tables are made? I know it's not part of the project, but it would help beginners like me. Thank you very much.

**Comment by szporwolik** [comment]
The tables are shortly described at https://github.com/szporwolik/perun#mysql-database-structure 

There are thousands examples about the PHP+MySQL integration all over the internet; I'm not sure if we need another one.
Example: https://stackoverflow.com/questions/15251095/display-data-from-sql-database-into-php-html-table 

What I can agree to is that this shall be better documented inside Readme.

**Comment by ghost** [comment]
Thank you very much, I will study it carefully (I don't have much idea about PHP), one question, by means of command line, can you make it auto start when opening the program?

**Comment by szporwolik** [comment]
I'm not sure what you are asking about exactly, but yes - some of the parameters can be set from command line while launching the app, see: https://github.com/szporwolik/perun#windows-app---command-line-arguments-for-expert-users

**Comment by ghost** [comment]
Sorry, I am not explaining myself well, (my English is not very good). When you open the app, you have to click on "Start", I don't know if there is a way that when you open the app, you automatically press "start" (a kind of autoconnect, for example "perun.exe -start")

**Comment by szporwolik** [comment]
OK, now it's clear.

Will think about with the next releases, as I remember there were some reason to force player to manually start the app.

**Comment by ghost** [comment]
Thanks again, the idea of "autostart" is because I have a dedicated server with remote start, and of course, Perun does not start automatically :-)
Again, thanks a lot!

**Comment by szporwolik** [comment]
#39

**Comment by szporwolik** [comment]
Basic example of PHP integration added to https://github.com/szporwolik/perun/blob/master/04_Misc/05_PHP_Example/index.php
