### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by davidp57** [szporwolik/perun#51]
Not an issue, yet.
In the commit #9569762eac2a5822b9c0852621ca337e6780412a, you separated Perun's LUA configuration from its code.
That's a good thing to do imho.
However, the generic name you chose ("Config") could lead to collisitions with other scripts, in the future (or maybe now, with scripts we don't know yet).
I'd recommend initializing the "Perun" table in the configuration file, and using it (completing it with code) in the code script.

**Comment by szporwolik** [comment]
Yes, good point. Will be fixed.
