### ISSUE TITLE
Error when the name of a player contains a single quote (')

### ISSUE THREAD

**Issue by davidp57** [szporwolik/perun#54]
When a player name contains a single quote (as for example my friend **Ti'rco**), the json containing the list of players cannot be parsed and an error is thrown back to the user in the windows app.
Here's the exception that's thrown :

[error.zip](https://github.com/szporwolik/perun/files/5991221/error.zip)

Here's a saved payload that triggers the bug :

[Perun_LogContent_2021-02-16-00-00-00.0000000-01-00.zip](https://github.com/szporwolik/perun/files/5991218/Perun_LogContent_2021-02-16-00-00-00.0000000-01-00.zip)

This is easily solved by removing the quotes around the payload property value :

[test.zip](https://github.com/szporwolik/perun/files/5991236/test.zip)

(I said "easily" but I know that it's never as simple as just saying it ^^ - the JSON is created in the LUA script, which is probably difficult to correct)

**Comment by szporwolik** [comment]
Yes, I've seen similar story recently with " in the user name. Will take a look into that.

**Comment by szporwolik** [comment]
This is not the best, but this is the quickest.
