### ISSUE TITLE
No update when mission changes on the server

### ISSUE THREAD

**Issue by davidp57** [szporwolik/perun#59]
I'm not 100% sure, but it seems that the LUA hook only refreshes the mission and slots data at start, and when reconnecting to the TCP socket.
Does that mean what I think ? If the server switches mission (without restarting the server itself, only loading a new mission) then the mission and slots data will not be updated ?

**Comment by szporwolik** [comment]
No worries - Perun-hook.lua line 626 ; once the mission is reloaded the slots and mission data is send.

**Comment by davidp57** [comment]
Oh, I didn't see this. Thanks !
