### ISSUE TITLE
12.1 changes in main branch, latest releases only shows 12.0

### ISSUE THREAD

**Issue by thebgpikester** [szporwolik/perun#66]
There's a mix of 12.1 and 12.0 and if you take the mix you end up with database issues because the version will be out. The 12.1 verison of the app is not in latest releases.

**Comment by szporwolik** [comment]
Yes, while it's always preffered to use tagged version of the code - https://github.com/szporwolik/perun/releases/tag/v0.12.0 this shall work without any troubles.

**Comment by szporwolik** [comment]
Please use the tagged version of the code https://github.com/szporwolik/perun/releases/tag/v0.12.0 , this shall work without any troubles.

**Comment by szporwolik** [comment]
Please use tagged version of the code: https://github.com/szporwolik/perun/releases/tag/v0.12.0 , this shall work without any issues.
