### ISSUE TITLE
integrate new DCS events from 2.7 into hook and DB

### ISSUE THREAD

**Issue by thebgpikester** [szporwolik/perun#67]
LandingQualityMark is especially new and now that we can get the LSO grades with a player you can do a lot with that in a database, There's some others that im still investigating.

**Comment by ags313** [comment]
Sounds interesting. Did you see a list of new events that were added? We should be able to support the interesting ones!

**Comment by thebgpikester** [comment]
https://wiki.hoggitworld.com/view/DCS_singleton_world 
S_EVENT_LANDING_QUALITY_MARK = 36, 
That seems the most interesting worth using. The others, not so much use for statistics, but this holds the LSO's grade on all planes who land or engage with the LSO comms and get waved off.


Previously this was in a comment with no initiator so couldnt be used (easily). Post 2.7 it was moved to its own mark. Still has AI using it, so you have to filter those.
My second favourite is the landing after ejection, which fires when the avatar lands on the floor. You can get his location of additional gameplay, but its not that interesting for stats. Same goes for the weapon add - not interesting for stats. Player comment is useless.

**Comment by ags313** [comment]
DCS.onGameEvent will not emit that event. 
This is sad, but I can't do much - there are some events that are not exported to the server event layer.
